- title: "Solve Mineswepper with DQN"
  article_link: "https://tonnonssi.github.io/projects/1-minesweeper"
  year: "March, 2024-"
  dev_tool:
    - "Python"
    - "Pytorch"
    - "Web"
  abstract: "Solved Minesweeper using DQN. Trained a model with an average win rate of 84%(easy level). Solved theoretical minesweeper, web for deployment. <br>-<br>강화학습으로 지뢰찾기 문제를 해결했다. 초급 기준 평균 승률 84% 모델을 학습시켰고 배포를 위한 웹, 지뢰찾기의 이론적 풀이를 진행했다."
  github: "https://github.com/Tonnonssi/-RL-Minesweeper"
  # image: "../assets/images/ProjectThumbnail/Minesweeper.png"

- title: "Solve Gomoku with AlphaZero"
  article_link: "https://tonnonssi.github.io/projects/2-omok"
  year: "October, 2024-"
  dev_tool:
    - "Python"
    - "c++"
    - "Pytorch"
    - "Arduino"
    - "Web"
  abstract: "This project applies AlphaZero to a real-world Gomoku game with a robotic arm."
  github: "https://github.com/Tonnonssi/AiGO"
  pdf: "https://raw.githubusercontent.com/Tonnonssi/AiGO/main/img/report.pdf"

- title: "Solve TicTacToe with Dual Agent Methods"
  article_link: "https://tonnonssi.github.io/projects/3-tictactoe"
  year: "October, 2024 - February, 2025"
  dev_tool:
    - "Python"
    - "c++"
    - "Pytorch"
    - "Arduino"
  abstract: "This project applies various dual agent methods to a real-world tictactoe game with a CNC model."
  github: "https://github.com/Tonnonssi/TicTacToeArtist"
  pdf: "https://raw.githubusercontent.com/Tonnonssi/TicTacToeArtist/main/img/report.pdf"

